FROM python:3.10-slim

RUN apt-get update && apt-get install -y libgomp1 gcc g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./src /app/src
COPY ./models /app/models
COPY requirements.txt ./

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH="/app"

CMD ["python", "src/kafka_consumer.py"]
