version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflowpass
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    depends_on:
      - postgres
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql://mlflow:mlflowpass@postgres:5432/mlflow_db
      MLFLOW_ARTIFACT_ROOT: /mlflow/artifacts
    ports:
      - "5000:5000"
    volumes:
      - mlflow-artifacts:/mlflow/artifacts

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fraud-fastapi
    depends_on:
      - kafka
      - postgres
      - mlflow
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      DATABASE_URL: postgresql://mlflow:mlflowpass@postgres:5432/mlflow_db
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./models:/app/models

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: fraud-consumer
    depends_on:
      - kafka
      - fastapi
      - postgres
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      DATABASE_URL: postgresql://mlflow:mlflowpass@postgres:5432/mlflow_db
      MLFLOW_TRACKING_URI: http://mlflow:5000
      PYTHONPATH: "/app"
    volumes:
      - ./src:/app/src
      - ./models:/app/models

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    depends_on:
      - fastapi
    environment:
      FASTAPI_URL: http://fastapi:8000
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src

volumes:
  pgdata:
  mlflow-artifacts:
